- uses: Platane/snk@v3
  with:
    # github user name to read the contribution graph from (**required**)
    # using action context var `github.repository_owner` or specified user
    github_user_name: ${{dreamtraveller1314}}

    # list of files to generate.
    # one file per line. Each output can be customized with options as query string.
    #
    #  supported options:
    #  - palette:           A preset of color, one of [github, github-dark, github-light]
    #  - color_snake:       Color of the snake
    #  - color_dots:        Coma separated list of dots color.
    #                       The first one is 0 contribution, then it goes from the low contribution to the highest.
    #                       Exactly 5 colors are expected.
    #  - color_background:  Color of the background (for gif only)
    outputs: |
      # Format: path/to/file.svg?color_snake=SNAKE_COLOR&color_dots=COLOR1,COLOR2,COLOR3,COLOR4,COLOR5
      dist/github-snake.svg?color_snake=#FF69B4&color_dots=#FFE4E1,#FFB6C1,#FFC0CB,#FF69B4,#FF1493
