      - name: generate-snake-game
        uses: Platane/snk@v3
        with:
          github_user_name: dreamtraveller1314
          outputs: |
            dist/github-snake.svg?color_snake=#FF69B4&color_dots=#FFF0F5,#FFB6C1,#FF69B4,#FF1493,#C71585
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#FF69B4&color_dots=#30122e,#702058,#9d357a,#c94da1,#f066cc
            dist/ocean.gif?color_snake=#FF1493&color_dots=#FFF0F5,#FFB6C1,#FF69B4,#FF1493,#C71585&color_background=#1a1a1a
